default:
  G_SSID_PL: "1eYw8Q-DXnlHDxvFFUwyMlREjkey-bbx_6Xw1DdjjcMI"
  G_SHTNAME_PL: "PL"
  G_EMAIL: "takahirohashimoto@labprojectllc.com"
  G_SSID_PERF: "1Yr4VhDGCc8cHQ5dPaTzVTo13et1l-qeF00LBBJsT9s8"
